name: apartmentinspection
description: "Apartment Inspection Application with Flutter, Firebase, GetX"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1


#<---------------------------Environment Version------------------------>
environment:
  sdk: ^3.5.4

#<---------------------------Dependencies------------------------>
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get:
  firebase_core:
  cloud_firestore:
  firebase_auth:
  firebase_storage:
  flutter_screenutil:
  skeletonizer: ^1.4.3
  flutter_local_notifications: ^19.1.0
  intl:
  awesome_snackbar_content: ^0.1.5
  image_picker: ^1.1.2
  signature:
  pdf: ^3.11.3
  printing: ^5.14.2
  google_fonts: ^6.2.1
  permission_handler: ^12.0.0+1
  widgets_to_image: ^1.0.0
  syncfusion_flutter_pdfviewer:
  path_provider:
  flutter_slidable:
  animate_do: ^4.2.0
  flutter_spinkit: ^5.2.1
  mailer:

  #<---------------------------Localization------------------------>
  flutter_localizations:
    sdk: flutter

#<---------------------------Dev Dependencies------------------------>
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

#<---------------------------Assets------------------------>
flutter:
  generate: true
  uses-material-design: true
  assets:
     - assets/images/
     - assets/fonts/Roboto-Regular.ttf

  #<---------------------------Font Assets------------------------>
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
