// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxe6rxlTl8xn-7Mk5l-5q3gkzLi34m4tY',
    appId: '1:14521645431:web:84a18d850859830cf18972',
    messagingSenderId: '14521645431',
    projectId: 'apartment-inspection',
    authDomain: 'apartment-inspection.firebaseapp.com',
    storageBucket: 'apartment-inspection.firebasestorage.app',
    measurementId: 'G-7PBDGL8KSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu9svUqJvnA_Js_ong9_HQhuRunpV4QW8',
    appId: '1:14521645431:android:3543872e4fe3f38df18972',
    messagingSenderId: '14521645431',
    projectId: 'apartment-inspection',
    storageBucket: 'apartment-inspection.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMmJFV32Gt7JsYctQMzahA3Rg9Wv1HJYs',
    appId: '1:14521645431:ios:892f939b9c48e42df18972',
    messagingSenderId: '14521645431',
    projectId: 'apartment-inspection',
    storageBucket: 'apartment-inspection.firebasestorage.app',
    iosBundleId: 'com.lzs.apartmentinspection',
  );
}
